name: Build & Push to container registry

on:
  release:
    types: [created]
  push:
    branches:
      - "main"

jobs:
  build:
    uses: kagchi/workflows/.github/workflows/docker-build.yaml@main
    permissions:
      packages: write
      contents: read
    secrets: inherit
    with:
      PLATFORMS: linux/amd64